### ISSUE TITLE
Ignore chrome extensions

### ISSUE THREAD

**Issue by mike-north** [DockYard/ember-service-worker-cache-first#6]
It would be nice if developers didn't have to sift through this noise
<img width="596" alt="screen shot 2016-12-03 at 10 32 43 pm" src="https://cloud.githubusercontent.com/assets/558005/20862356/7bb3874a-b9a8-11e6-98fa-db3ba394a707.png">

Easy fix is regex checking URLs as they fly by, before attempting to send the request off the the SW cache. 
```js
if (/^https?\:\/{2}/.test(url)) {
   // ...
}
```
this will filter out `chrome-extension://*` junk

**Comment by ghost** [comment]
Closed via #7!
