### ISSUE TITLE
No information on this libraries functionality

### ISSUE THREAD

**Issue by AKST** [DockYard/ember-service-worker-cache-first#9]
## Version
0.6.1

## Test Case
Read the readme

## Steps to reproduce
go to the [read me](https://github.com/DockYard/ember-service-worker-cache-first)

## Expected Behaviour
Expected to see description of library functionality

## Actual Behaviour
Did not see description of library functionality

**Comment by ehariprasad** [comment]
Not clear with the purpose of this library. Just based on name, i think it's for cache the api urls just as ember-service-worker-cache-fallback does the same in offline mode. am i right ?
